CREATE TABLE `permissao_acesso` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nome` varchar(17) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci